"""Program-spec to runnable code renderer.

A program spec is a JSON dict describing the full Level 0 pipeline:
  preprocessing -> feature extraction (optional) -> model -> training -> decode

`render_spec_to_code` writes a `run.py` to `out_dir` that, when invoked with
`--run-dir`, trains and evaluates the program and writes `result.json` atomically.

`fingerprint_spec` returns a structural SHA-256 hash. Two specs with the same
structure but different numeric hyperparameters get the same fingerprint;
specs with different operator/family choices get different fingerprints. Used
by `framework.constraints.ast_tabu` to refuse near-duplicates.

Currently supported model families (BP-Inference-EVOLVE adapter, PPG-only):
  - ridge_regressor_cv: ROCKET-family kernels + RidgeCV  (bp_inference.minirocket)
  - runet_attn:         rU-Net + STFT + attention        (bp_inference.runet_attn)
  - resunet_sa:         self-attention ResUNet            (bp_inference.resunet_sa)
  - mamba_ssm:          selective state-space U-Net       (bp_inference.mamba_ssm)

Adding a new family is a 2-line change: add an entry to FAMILY_ENTRY_POINTS,
implement the corresponding `run_from_dir(run_dir, data_root)` function in the
target module. The engine itself is problem-agnostic; this table is the only
place it names the adapter.

Spec: FRAMEWORK.md Section 2.
"""
import hashlib
import json
from pathlib import Path


FAMILY_ENTRY_POINTS: dict[str, tuple[str, str]] = {
    "ridge_regressor_cv": ("bp_inference.minirocket", "run_from_dir"),
    "runet_attn": ("bp_inference.runet_attn", "run_from_dir"),
    "resunet_sa": ("bp_inference.resunet_sa", "run_from_dir"),
    "mamba_ssm": ("bp_inference.mamba_ssm", "run_from_dir"),
}

# Which compute each family needs. MiniRocket is numpy + sklearn (CPU-only); a
# CPU-only task must NOT request a GPU (it idles the GPU -> RC cancels it). The
# neural families train on the GPU. The batch renderer splits the manifest by
# this so CPU seeds go to `short` and GPU seeds to `gpu`.
FAMILY_COMPUTE: dict[str, str] = {
    "ridge_regressor_cv": "cpu",
    "runet_attn": "gpu",
    "resunet_sa": "gpu",
    "mamba_ssm": "gpu",
}


_RUN_PY_TEMPLATE = '''"""Auto-generated by framework.render. Do not edit by hand.

Loads spec.json from --run-dir, dispatches to {entry_module}.{entry_fn},
which trains the program and writes result.json into --run-dir atomically.

`project_root` is located by walking up from this file's directory until a
directory containing `framework/__init__.py` is found. This makes the
template work at any nesting depth under `experiments/`.
"""
from pathlib import Path
import argparse
import sys

if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent
    while project_root != project_root.parent:
        if (project_root / "framework" / "__init__.py").exists():
            break
        project_root = project_root.parent
    else:
        raise RuntimeError(
            "could not locate project root (no framework/__init__.py "
            "found in any ancestor of " + str(Path(__file__).resolve()) + ")")
    sys.path.insert(0, str(project_root))

    from {entry_module} import {entry_fn}

    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--data-root", type=Path,
                        default=project_root / "data" / "raw")
    args = parser.parse_args()

    # Always emit a result.json so failures are visible after a git pull (the
    # SLURM logs/ dir is gitignored). On crash, record the traceback and exit 1
    # so SLURM still marks the task FAILED.
    import json as _json, traceback as _tb
    try:
        {entry_fn}(args.run_dir, args.data_root)
    except Exception:
        tb = _tb.format_exc()
        (args.run_dir / "result.json").write_text(_json.dumps(
            {{"name": args.run_dir.name, "failed": True, "error": tb}}, indent=2))
        print(tb, flush=True)
        raise SystemExit(1)
'''


def render_spec_to_code(spec: dict, out_dir: Path) -> Path:
    """Render `spec` into a runnable `run.py` + `spec.json` in `out_dir`.

    Returns the path to the generated `run.py`.

    Raises:
        ValueError: if `spec["model"]["family"]` is not in FAMILY_ENTRY_POINTS.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    family = spec.get("model", {}).get("family")
    if family not in FAMILY_ENTRY_POINTS:
        raise ValueError(
            f"unsupported model family: {family!r}. "
            f"Supported: {sorted(FAMILY_ENTRY_POINTS.keys())}")

    entry_module, entry_fn = FAMILY_ENTRY_POINTS[family]

    spec_path = out_dir / "spec.json"
    spec_path.write_text(json.dumps(spec, indent=2, sort_keys=True))

    run_py = out_dir / "run.py"
    run_py.write_text(_RUN_PY_TEMPLATE.format(
        entry_module=entry_module,
        entry_fn=entry_fn,
    ))
    return run_py


def _structural_view(obj):
    """Strip numeric leaf values, keep structural skeleton.

    Rules:
      - dicts: recurse into values, keep keys (sorted in fingerprint stage)
      - lists: preserve order, recurse into elements
      - None: kept as None
      - bool: kept (decision-like, not a hyperparameter)
      - int / float: replaced with placeholder '<num>'
      - str: kept as-is (operator names, family choices are structural)
      - other types: replaced with type-tagged placeholder
    """
    if isinstance(obj, dict):
        return {k: _structural_view(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_structural_view(v) for v in obj]
    if obj is None:
        return None
    if isinstance(obj, bool):
        return obj
    if isinstance(obj, (int, float)):
        return "<num>"
    if isinstance(obj, str):
        return obj
    return f"<{type(obj).__name__}>"


def fingerprint_spec(spec: dict) -> str:
    """Structural SHA-256 hash. Same structure but different numeric
    hyperparameters -> same fingerprint. Different families, different
    operator names, different keys -> different fingerprints.
    """
    skeleton = _structural_view(spec)
    canonical = json.dumps(skeleton, sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
